### ISSUE TITLE
[core] Strategy/Roadmap 1.0 (Draft)

### ISSUE THREAD

**Issue by pozylon** [unchainedshop/unchained#115]
After many discussins and various issues, hearing to the community and other developers, we have laid out a general roadmap on how we want to transform Unchained. 

**We want to get off the meteor train. Why?**
Using emerging technologies and architectures like typescript, jest, serverless configurations has been hard with a runtime that uses a custom bundler, a proprietary package manager and an always older than current node.js version. We are not convinced of the future of meteor and we think going a more agnostic way would open up the whole system to many more developers. Too many times we have faced meteor bias (does that scale? is that still maintainted?) that kept developers from using unchained in their next e-commerce projects.

# Vision: Become Node.js Framework agnostic

We should refactor unchained before we go 1.0 and this is a first try for an architectural draft. The current logic around helpers and direct module-to-module dependencies is not good enough in terms of separation of concerns and modularity. When doing this kind of big refactorings, it's key to do it in small steps and with a clear scope in min.

In Scope:
- Dataloader + TS + Context (Big GraphQL Refactor)
- Delete Fixtures / Factories
- Delete Migrations
- Migrate from Meteor Files
- Migrate from Accounts
- Migrate from all the other packages like SyncedCron (#213, #214, #215, #216)
- Move Code from Packages to one single NPM Package

Out Of Scope:
- MongoDB / ORM / Query Builders (we will use the nodejs mongodb native library and we will not try to make unchained db agnostic)
- Migrate from Simple Schema Validation (we will still use simple-schemas for the moment)
- Yarn Workspaces / Multi-package approach, ... (we will not change to some sophisticated workspace or package monster architecture)
- Deno :) (we will not use something else than Node.js for the moment)
- New Migration Tool (we will not evaluate and add a sophisticated migration tool and instead use a very lightweight custom one from a project)
- API Decoupling (We will not try to split up the GraphQL API definition to various modules and instead keep the GraphQL part in one single module like it is now)

## Milestones:

1. Dataloaders & Services
2. No external Meteor Packages (Accounts, Files, ...)
3. New NPM Package @unchainedshop/unchained

## Benefits:

1. Unit testable core modules -> no helpers, domain logic as functional code
2. Interdependencies / Modularity -> Extract glue code to it's own right (checkout flow for ex.), making the whole system more flexible and organized
3. Performance: Solve 1+n performance problem with Dataloaders for all DB access

# Architecture

## Layers

1. Core Module, a core module is usually built around dataloaders for db entities and is named after that, so it could be like „Order“
2. Services (Cross-module functionality), a service’s name could be „checkout“, „search“, „breadcrumbs“, …
3. GraphQL (Uses services and modules to expose unchained’s functionality through GraphQL resolvers and queries)
4. Platform (Loads configuration, modules, loads services, instantiates API and db access)

### Core Module Definition

- Creates dataloaders
- Exposes schemas, constants & unit-testable stateless functions
- Takes a Factory function that takes configuration and request context, creates a set of functions with domain logic

### Services Definition:

- Creates asynchronous reading and writing
- Is free to use any module as long as the context is used to get the needed data

```
return (ctx) => {
  async addProductToCart({ orderId, productId }) {
    const product = await ctx.modules.products.findProductById(productId)
    const resolvedProduct = await ctx.modules.products.resolveOrderableProduct(product, { quantity, configuration })
    return ctx.modules.orders.upsertPosition({ … });
  }
}
```

### API Definition (GraphQL):

- Creates queries and mutations, is free to use services and modules to generate types, schema and resolvers
- Combines writing and reading services
- Responsible for Error & Exception Handling

Resolver example:

```
export default async addCartProduct(_, { orderId, productId, quantity }, { services, modules }) {
    if (quantity < 1) throw new OrderQuantityTooLowError({ quantity });
    const orderPositionId = await services.addProductToCart({ orderId, productId, quantity, configuration });
    if (!orderPositionId)  throw new Error({ … });
    return modules.orders.findOrderPositionById(orderPositionId)
  }
}
```

### Platform

- Establishes MongoDB & Redis Connections, loads configuration
- Uses the API Layer to create the global context (Graphql = Apollo Context)
- Instantiates all Core Modules

```
const warehousing = createWarehousingContext({ request, user, db, moduleConfig }):
const …
const ctx = { modules: { warehousing }, services }…
```

## Side Quests

Side-Quest 1 (Developer Experience): Introduction of Typescript as it now is clearly the most popular language choice in the node.js ecosystem, use for plugin system first, after that migrate files when touched.

Side-Quest 2 (Extendability): Improvements to the plugin architecture slowly migrating to a functional and pure strategy.

**Comment by pozylon** [comment]
I've closed all issues that were centered around refactoring various parts of the system as they have become stale. We will focus all our energy on tests and our main quest and pickup the ideas during and after.

**Comment by schmidsi** [comment]
This could be an interesting module for authentication: https://github.com/jkettmann/graphql-passport

**Comment by pozylon** [comment]
## Draft Refactoring Proposal

### Step 1: package-by-package PR's:

Goal: Reduce all code in collection helpers to wrappers and add unit tests.

**Current code structure:**

```
Product.helpers({
   author() {
     ... business logic like return Users.findOne({ _id: this.authorId })
   }
})

Users.helpers({
   primaryEmail() {
     ... business logic
   }
})
```

**to** 

```
Users.findById = async (userId) => { ... db fetch logic ... }
```

```
import { primaryEmail } from './utils';
import { findById } from './db';

Product.helpers({
   author() {
     return findById(this.authorId);
   }
})

Users.helpers({
   primaryEmail() {
     return primaryEmail(this);
   }
})

export { primaryEmail, findById };
```

then unit test primaryEmail function.


### Step 2: Get rid of collection helpers

Goal: No package depends on collection helpers dependency anymore

1. Move the helper functions to explicit Apollo Types
2. Replace all occurences of helpers used in other packages with the explicit static function
```
const user = Users.findOne({ _id: ... });
return user.primaryEmail()
```

becomes
```
const userObject = CoreUsers.findById(...)
return CoreUsers.primaryEmail(userObject)
```
3. Some utils are now too heavy-weight and you can see explicitly that they add cross-package dependencies, these utils shall now be moved to a new "services" package so doing a checkout is now more like this:

```
import { CheckoutService } from 'meteor/unchained:services';

mutation checkoutCart = async (...) => {
  const cartId = CoreUsers.currentCartId(userObject);
  try {
 await CheckoutService.checkout(cartId);
...}
  return CoreOrders.findById(cartId);
}
```

### Step 3: Get rid of meteor mongo

Goal: 10-100X better performance, solve 1+n problem with Dataloader

```
export const CoreUsers = () => {
   ...instantiate loader class, return object with findById backed by that loader...
}
```

```
mutation checkoutCart = async (...) => {
  const cartId = CoreUsers.currentCartId(userObject);
  ...
}
```
becomes 
```
mutation checkoutCart = async (..., { core, services }) => {
  const cartId = core.users.currentCartId(userObject);
  try {
 await services.checkout(cartId);
...}
  return core.orders.findById(cartId);
}
```

**Comment by pozylon** [comment]
We are closer than ever to the goal:

In Scope:

- [x] ~Dataloader + TS + Context (Big GraphQL Refactor)~
- [x] Delete Fixtures / Factories
- [x] Delete Migrations
- [ ] Migrate from Meteor Files
- [x] Migrate from Accounts
- [x] Migrate from all the other packages like SyncedCron (Get rid of "meteor/percolate:migrations" #213, Get rid of "littledata:synced-cron" #214, Get rid of "meteor/dburles:factory" #215, Get rid of "aldeed:schema-index" #216)
Move Code from Packages to one single NPM Package
- [ ] Refactoring packages around modules and services without helpers

Dataloaders are not the highest priority anymore as the system currently performs quite good without it but we will hold on to the goal for Unchained 1.1
